### ISSUE TITLE
Vertex indexing off by one

### ISSUE THREAD

**Issue by akx** [threadException/renderer#1]
Based on [Wikipedia's docs about the .obj format](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_indices), `f` lines are 1-indexed.

It doesn't look like the loader takes that into account:
https://github.com/threadException/renderer/blob/dea960baa39c9d5e1a1dcf1305ad36d919c05235/model.cpp#L24-L29
so the indices in the `mesh` function are probably also wrong.
https://github.com/threadException/renderer/blob/dea960baa39c9d5e1a1dcf1305ad36d919c05235/model.cpp#L36-L40

That could explain the stray lines from the monkey's chin to its ear in https://raw.githubusercontent.com/threadException/renderer/main/screenshot.png ...

**Comment by 0jk6** [comment]
Hi, Thanks for pointing this out. Just fixed it here https://github.com/threadException/renderer/commit/01ad5cc07865ede8dd7079d32880d8a8908e9e0f
